# Generated by Django 5.1.7 on 2025-04-06 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.CharField(blank=True, max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('operador', 'Operador'), ('personal', 'Personal')], default='cliente', max_length=20)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
    ]
