# Generated by Django 5.1.7 on 2025-04-21 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'super admin'), ('tecnico', 'tecnico'), ('administrador', 'administrador')], default='super_admin', max_length=100),
        ),
    ]
