# Generated by Django 5.1.7 on 2025-04-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('super_admin', 'super admin'), ('tecnico', 'tecnico'), ('administrador', 'administrador')], default='uper_admin', max_length=100),
        ),
    ]
