# Generated by Django 5.1.7 on 2025-04-26 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(max_length=100)),
                ('numero_tramite', models.IntegerField(blank=True, null=True)),
                ('rutasOperar', models.TextField(blank=True, null=True)),
                ('fecha_validezI', models.DateField()),
                ('fecha_validezF', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tipo_tramite', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('verificado', 'verificado'), ('observado', 'observado'), ('ingresado', 'ingresado')], default='ingresado', max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('flag', models.CharField(choices=[('nuevo', 'nuevo'), ('eliminado', 'eliminado')], default='nuevo', max_length=20)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.afiliado')),
            ],
        ),
    ]
