# Generated by Django 5.1.7 on 2025-05-12 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('afiliados', '0001_initial'),
        ('operador', '0001_initial'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('flag', models.CharField(choices=[('nuevo', 'nuevo'), ('eliminado', 'eliminado')], default='nuevo', max_length=20)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.afiliado')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
                ('rutas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.rutas')),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(max_length=100)),
                ('numero_tramite', models.IntegerField(blank=True, null=True)),
                ('numero_fojas', models.IntegerField(blank=True, null=True)),
                ('fecha_validezI', models.DateField()),
                ('fecha_validezF', models.DateField(blank=True, null=True)),
                ('numero_comprobante', models.CharField(blank=True, null=True)),
                ('verificarPago', models.BooleanField(default=False)),
                ('monto', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('tipo_tramite', models.CharField(max_length=100)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('verificado', 'verificado'), ('observado', 'observado'), ('ingresado', 'ingresado')], default='ingresado', max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('flag', models.CharField(choices=[('nuevo', 'nuevo'), ('eliminado', 'eliminado')], default='nuevo', max_length=20)),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operador.operador')),
            ],
        ),
    ]
