# Generated by Django 5.1.7 on 2025-04-08 02:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.CharField(max_length=100)),
                ('rutasOperar', models.TextField(max_length=100)),
                ('fecha_validezI', models.DateField()),
                ('fecha_validezF', models.DateField(blank=True, null=True)),
                ('numero_deposito', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('numero_fojas', models.IntegerField(default=0)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ingresado', 'ingresado'), ('anulado', 'anulado'), ('entregado', 'entregado'), ('proceso', 'proceso')], default='ingresado', max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('flag', models.CharField(choices=[('nuevo', 'nuevo'), ('eliminado', 'eliminado')], default='nuevo', max_length=20)),
                ('tipo_tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.tipo_tramite')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
        ),
    ]
