# Generated by Django 5.1.7 on 2025-04-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='fecha_validezF',
            field=models.DateField(blank=True, null=True),
        ),
    ]
