# Generated by Django 5.1.7 on 2025-04-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_alter_tramite_fecha_validezf'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
