# Generated by Django 5.1.7 on 2025-06-03 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costo',
            name='precio',
            field=models.IntegerField(blank=True),
        ),
    ]
