# Generated by Django 5.1.7 on 2025-04-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='tiene_vehiculo',
            field=models.BooleanField(default=False),
        ),
    ]
