# Generated by Django 5.1.7 on 2025-05-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletramite',
            name='afiliado',
            field=models.CharField(blank=True, null=True),
        ),
    ]
