# Generated by Django 5.1.7 on 2025-04-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='numero_tramite',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
    ]
