# Generated by Django 5.1.7 on 2025-04-09 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_tramite_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'ingresado'), ('anulado', 'anulado'), ('entregado', 'entregado'), ('aprobado', 'aprobado')], default='ingresado', max_length=50),
        ),
    ]
