# Generated by Django 5.1.7 on 2025-05-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='banco',
            field=models.DateField(blank=True, max_length=255, null=True),
        ),
    ]
