# Generated by Django 5.1.7 on 2025-04-07 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_tramite_monto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='tramite',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(choices=[('ingresado', 'ingresado'), ('anulado', 'anulado'), ('entregado', 'entregado'), ('proceso', 'proceso')], default='ingresado', max_length=50),
        ),
        migrations.AddField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='tramite.tipo_tramite'),
            preserve_default=False,
        ),
    ]
