# Generated by Django 5.1.7 on 2025-04-30 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_tramite_tiene_vehiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='monto',
            field=models.FloatField(default=0),
        ),
    ]
