# Generated by Django 5.1.7 on 2025-05-27 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_tramite_costo_tarjeta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='costo_tarjeta',
        ),
        migrations.AddField(
            model_name='detalletramite',
            name='costo_tarjeta',
            field=models.IntegerField(default=0),
        ),
    ]
