# Generated by Django 5.1.7 on 2025-04-10 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_alter_tramite_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='fecha_entrega',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='numero_fojas',
        ),
    ]
