# Generated by Django 5.1.7 on 2025-04-19 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_tramite_numero_tramite_tramite_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tramite',
            name='rutasOperar',
            field=models.TextField(blank=True, null=True),
        ),
    ]
