# Generated by Django 5.1.7 on 2025-05-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_alter_tramite_banco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='banco',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
