# Generated by Django 5.1.7 on 2025-05-13 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0003_alter_detalletramite_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletramite',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
