# Generated by Django 5.1.7 on 2025-04-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_tramite_monto_tramite_rutasoperar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
