# Generated by Django 5.1.7 on 2025-04-30 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_alter_tramite_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='monto',
            field=models.IntegerField(default=0),
        ),
    ]
