# Generated by Django 5.1.7 on 2025-04-07 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_tipo_tramite_tramite_observaciones_and_more'),
        ('usuarios', '0002_usuario_contraseña_usuario_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='numero_fojas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tramite',
            name='usuario',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='usuarios.usuario'),
            preserve_default=False,
        ),
    ]
