# Generated by Django 5.1.7 on 2025-04-11 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
        ('tramite', '0004_remove_tramite_fecha_entrega_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='vehiculo',
        ),
        migrations.AddField(
            model_name='tramite',
            name='afiliado',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='afiliados.afiliado'),
            preserve_default=False,
        ),
    ]
