# Generated by Django 5.1.7 on 2025-05-13 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0004_alter_detalletramite_fecha_creacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalletramite',
            name='rutas',
            field=models.CharField(blank=True, null=True),
        ),
    ]
