# Generated by Django 5.1.7 on 2025-05-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_alter_detalletramite_rutas'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha_observacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
