# Generated by Django 5.1.7 on 2025-04-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_tramite_numero_fojas_tramite_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
