# Generated by Django 5.1.7 on 2025-04-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_remove_tramite_vehiculo_tramite_afiliado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='tipo_tramite',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='estado',
            field=models.CharField(choices=[('verificado', 'verificado'), ('observado', 'observado'), ('derivado', 'derivado'), ('derivar', 'derivar')], default='verificado', max_length=50),
        ),
        migrations.DeleteModel(
            name='Tipo_tramite',
        ),
    ]
