# Generated by Django 5.1.7 on 2025-05-06 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0005_alter_tramite_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='numero_comprobante',
            field=models.CharField(blank=True, null=True),
        ),
    ]
