# Generated by Django 5.1.7 on 2025-05-14 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_tramite_fecha_observacion_tramite_fecha_verificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='fecha_creacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
