# Generated by Django 5.1.7 on 2025-04-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_alter_tramite_monto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='monto',
        ),
    ]
