# Generated by Django 5.1.7 on 2025-04-11 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_alter_tramite_tipo_tramite_alter_tramite_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='monto',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='numero_deposito',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='rutasOperar',
        ),
    ]
