# Generated by Django 5.1.7 on 2025-05-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_tramite_fecha_pago_tramite_numero_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='verificaPago',
            field=models.BooleanField(default=False),
        ),
    ]
