# Generated by Django 5.1.7 on 2025-04-07 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0006_tramite_fecha_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='numero_deposito',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
