# Generated by Django 5.1.7 on 2025-04-07 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_tramite_numero_deposito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='usuario',
        ),
    ]
