# Generated by Django 5.1.7 on 2025-05-06 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_tramite_verificapago'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tramite',
            old_name='verificaPago',
            new_name='verificarPago',
        ),
    ]
