# Generated by Django 5.1.7 on 2025-04-22 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0007_remove_tramite_monto'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=6, max_digits=10),
            preserve_default=False,
        ),
    ]
