# Generated by Django 5.1.7 on 2025-05-06 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0008_rename_verificapago_tramite_verificarpago'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rutas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='rutasOperar',
        ),
        migrations.AddField(
            model_name='tramite',
            name='rutas',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tramite.rutas'),
        ),
    ]
