# Generated by Django 5.1.7 on 2025-04-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0008_tramite_monto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tramite',
            name='monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
