# Generated by Django 5.1.7 on 2025-05-07 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
        ('tramite', '0009_rutas_remove_tramite_rutasoperar_tramite_rutas'),
        ('vehiculo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='afiliado',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='rutas',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='tiene_vehiculo',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='vehiculo',
        ),
        migrations.CreateModel(
            name='DetalleTramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('flag', models.CharField(choices=[('nuevo', 'nuevo'), ('eliminado', 'eliminado')], default='nuevo', max_length=20)),
                ('afiliado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='afiliados.afiliado')),
                ('rutas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tramite.rutas')),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehiculo.vehiculo')),
            ],
        ),
    ]
