# Generated by Django 5.1.7 on 2025-05-07 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('federacion', '0001_initial'),
        ('tramite', '0010_remove_tramite_afiliado_remove_tramite_rutas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='federacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='federacion.federacion'),
            preserve_default=False,
        ),
    ]
