# Generated by Django 5.1.7 on 2025-05-07 02:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tramite', '0011_tramite_federacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalletramite',
            name='tramite',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tramite.tramite'),
            preserve_default=False,
        ),
    ]
