# Generated by Django 5.1.7 on 2025-05-12 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operador', '0001_initial'),
        ('tramite', '0012_detalletramite_tramite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='federacion',
        ),
        migrations.AddField(
            model_name='tramite',
            name='numero_fojas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='operador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='operador.operador'),
            preserve_default=False,
        ),
    ]
