# Generated by Django 5.1.7 on 2025-03-29 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afiliados', '0001_initial'),
        ('federacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='afiliado',
            name='federacion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='federacion.federacion'),
            preserve_default=False,
        ),
    ]
