# Generated by Django 5.1.7 on 2025-05-13 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=100)),
                ('placa', models.CharField(max_length=50)),
                ('tipo_transporte', models.CharField(choices=[('carga', 'carga'), ('pasajero', 'pasajero')], max_length=20)),
                ('chasis', models.CharField(blank=True, max_length=255, null=True)),
                ('capacidad', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('flag', models.CharField(choices=[('nuevo', 'nuevo'), ('eliminado', 'eliminado')], default='nuevo', max_length=20)),
            ],
        ),
    ]
