# Generated by Django 5.1.7 on 2025-05-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_marca_alter_vehiculo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiculo',
            name='marca',
            field=models.CharField(max_length=255),
        ),
    ]
