# Generated by Django 5.1.7 on 2025-06-13 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operador',
            name='region',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
